apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-deploy
  labels:
    app: myjavaapp
spec:
replicas:
  selector:
    matchLabels:
      app: myjavaapp
  template:
    metadata:
      labels:
        app: myjavaapp
    spec:
      containers:
      - name: myjavaappcontainer
        image: maha4iac/myonlinebooking:1
        
        ports:
        - containerPort: 8080
